services:
  db-accessor:
    build:
      context: ./db-layer/DbAccessor
      dockerfile: Dockerfile
    ports:
      - "7073:80"
    environment:
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      MONGODB_ATLAS_URI: ${MONGODB_ATLAS_URI}
      DB_URL: "http://db-accessor:80"

  account-manager:
    build:
      context: ./logic-layer/AccountManager
      dockerfile: Dockerfile
    ports:
      - "7072:80"
    environment:
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      BASE_API_URL: "http://db-accessor:80"
      OAUTH_CLIENT_ID: "f"
      OAUTH_CLIENT_ID_DB: "f"
      OAUTH_CLIENT_SECRET: "f"
      OAUTH_CLIENT_SECRET_DB: "f"
      OAUTH_SCOPE: "f"
      OAUTH_SCOPE_DB: "f"
      OAUTH_TENANT_ID_DB: "f"
      OAUTH_TENANT_ID: "f"
      CORS_ALLOWED_ORIGINS: '["http://localhost:3000"]'
      CONTAINER_NAME: "project-repo"

  logic:
    build:
      context: ./logic-layer/Logic
      dockerfile: Dockerfile
    ports:
      - "7071:80"
    environment:
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      BASE_API_URL: "http://db-accessor:80"
      CORS_ALLOWED_ORIGINS: '["http://localhost:3000"]'
      CONTAINER_NAME: "project-repo"

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:7071/api"
      REACT_APP_API_AUTH_URL: "http://localhost:7072/api"
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
